esphome:
  name: Shutters
  platform: ESP32
  board: esp32dev
  
  includes:
    - esphome-somfy/RFsomfy.h
    - esphome-somfy/SomfyRts.h
    - esphome-somfy/SomfyRts.cpp
  libraries:
    - FS
    - SPIFFS
    - https://github.com/Viproz/SmartRC-CC1101-Driver-Lib
    - SPI

# Add all your normal items

cover:
- platform: custom
  lambda: |-
    std::vector<Cover *> covers;

    int blindNumber = 5;

    for(int i = 0 ; i < blindNumber ; ++i) {
      auto newComp = new RFsomfy(i);
      App.register_component(newComp);
      covers.push_back(newComp);
    }

    // In case the rolling codes get messed up you can reset them here
    //covers[0]->set_code(50);
    
    return {covers};

  covers:
    - name: "Living room shutter"
      device_class: shutter
      id: somfy0
    - name: "Kitchen shutter"
      device_class: shutter
      id: somfy1
    - name: "Chamber shutter"
      device_class: shutter
      id: somfy2
    - name: "Office shutter"
      device_class: shutter
      id: somfy3
    - name: "Office window shutter"
      device_class: shutter
      id: somfy4
